# -*- coding: utf-8 -*-
"""
設定モジュール統合インポート

後方互換性を維持するため、すべての設定を統合インポートします。

使用方法:
    from python.config import INPUT_CSV_DIR, REPORTS_DIR
    from python.config import CURRENT_AGE, RETIREMENT_AGE
    from python.config import MONTE_CARLO_ITERATIONS
    from python.config import HIGH_RISK_THRESHOLD

または:
    from python.config.paths import INPUT_CSV_DIR
    from python.config.personal import CURRENT_AGE
    from python.config.simulation import MONTE_CARLO_ITERATIONS
    from python.config.constants import HIGH_RISK_THRESHOLD

最終更新: 2025年11月9日（Phase 1: config分割）
"""

# パス設定をインポート
from .paths import (
    BASE_DIR,
    DATA_DIR, DATA_INPUT_DIR, DATA_OUTPUT_DIR, DATA_ARCHIVE_DIR,
    INPUT_CSV_DIR,
    OUTPUT_CACHE_DIR, OUTPUT_TEMP_DIR, OUTPUT_GENERATED_DIR,
    REPORTS_DIR, REPORTS_COMPLETED_DIR, REPORTS_WORKING_DIR,
    DOCUMENT_DIR,
    # 後方互換性レイヤー
    IMAGE_DIR, OUTPUT_CSV_DIR, CSV_DIR,
    RESULT_DIR, RESEARCH_DIR, WORKING_DIR
)

# 個人情報をインポート（personal.pyがない場合はデフォルト値を設定）
try:
    from .personal import (
        CURRENT_AGE, CURRENT_YEAR, RETIREMENT_AGE, RETIREMENT_YEAR,
        WIFE_AGE, ELDEST_CHILD_AGE, YOUNGEST_CHILD_AGE,
        CURRENT_NISA, CURRENT_NISA_PRINCIPAL, CURRENT_NISA_GAIN,
        CURRENT_IDECO, CURRENT_IDECO_PRINCIPAL, CURRENT_IDECO_GAIN,
        CURRENT_COMPANY_STOCK, CURRENT_COMPANY_STOCK_COST, CURRENT_COMPANY_STOCK_GAIN,
        CURRENT_CASH, TOTAL_ASSETS,
        ANNUAL_INCOME_AFTER_TAX, MONTHLY_INCOME,
        ANNUAL_RENT, MONTHLY_RENT,
        CURRENT_MONTHLY_NISA, CURRENT_MONTHLY_IDECO, CURRENT_TOTAL_MONTHLY_INVESTMENT,
        MONTHLY_IDECO_2027, MONTHLY_INVESTMENT_2027,
        WIFE_MONTHLY_NISA,
        NISA_LIFETIME_LIMIT, NISA_LIFETIME_REMAINING,
        EDUCATION_COST, EDUCATION_COST_PER_CHILD,
        RETIREMENT_GOAL,
        MONTHLY_PENSION, ANNUAL_PENSION,
        MONTHLY_RETIREMENT_SHORTFALL
    )
except ModuleNotFoundError:
    import warnings
    warnings.warn(
        "personal.py not found. Please copy from personal.template.py:\n"
        "  cp python/config/personal.template.py python/config/personal.py\n"
        "Using default values for now.",
        UserWarning
    )
    # デフォルト値（テンプレートからコピーするまでの仮値）
    CURRENT_AGE = None
    CURRENT_YEAR = 2025
    RETIREMENT_AGE = 65
    RETIREMENT_YEAR = None
    WIFE_AGE = None
    ELDEST_CHILD_AGE = None
    YOUNGEST_CHILD_AGE = None
    CURRENT_NISA = 0.0
    CURRENT_NISA_PRINCIPAL = 0.0
    CURRENT_NISA_GAIN = 0.0
    CURRENT_IDECO = 0.0
    CURRENT_IDECO_PRINCIPAL = 0.0
    CURRENT_IDECO_GAIN = 0.0
    CURRENT_COMPANY_STOCK = 0.0
    CURRENT_COMPANY_STOCK_COST = 0.0
    CURRENT_COMPANY_STOCK_GAIN = 0.0
    CURRENT_CASH = 0.0
    TOTAL_ASSETS = 0.0
    ANNUAL_INCOME_AFTER_TAX = 0.0
    MONTHLY_INCOME = 0.0
    ANNUAL_RENT = 0.0
    MONTHLY_RENT = 0.0
    CURRENT_MONTHLY_NISA = 0.0
    CURRENT_MONTHLY_IDECO = 0.0
    CURRENT_TOTAL_MONTHLY_INVESTMENT = 0.0
    MONTHLY_IDECO_2027 = 0.0
    MONTHLY_INVESTMENT_2027 = 0.0
    WIFE_MONTHLY_NISA = 0.0
    NISA_LIFETIME_LIMIT = 1800.0
    NISA_LIFETIME_REMAINING = 1800.0
    EDUCATION_COST = 0.0
    EDUCATION_COST_PER_CHILD = 0.0
    RETIREMENT_GOAL = 0.0
    MONTHLY_PENSION = 0.0
    ANNUAL_PENSION = 0.0
    MONTHLY_RETIREMENT_SHORTFALL = 0.0

# シミュレーション設定をインポート
from .simulation import (
    MONTE_CARLO_ITERATIONS,
    EXPECTED_RETURN_STOCK, EXPECTED_RETURN_BOND, EXPECTED_RETURN_BALANCED,
    VOLATILITY_STOCK, VOLATILITY_BOND, VOLATILITY_BALANCED,
    DEFAULT_STOCK_RATIO, DEFAULT_BOND_RATIO,
    DEFAULT_SIMULATION_YEARS
)

# 統計定数をインポート
from .constants import (
    HIGH_RISK_THRESHOLD, MODERATE_RISK_THRESHOLD,
    EMERGENCY_FUND_MONTHS, MINIMUM_CASH_RESERVE_MONTHS,
    DEFAULT_INFLATION_RATE, HIGH_INFLATION_RATE,
    TYPICAL_FUND_FEE, HIGH_FEE_THRESHOLD,
    CAPITAL_GAINS_TAX_RATE,
    NISA_ANNUAL_LIMIT, NISA_GROWTH_LIMIT,
    IDECO_MONTHLY_LIMIT_EMPLOYEE, IDECO_MONTHLY_LIMIT_NO_PENSION, IDECO_WITHDRAWAL_AGE
)

__all__ = [
    # paths
    'BASE_DIR',
    'DATA_DIR', 'DATA_INPUT_DIR', 'DATA_OUTPUT_DIR', 'DATA_ARCHIVE_DIR',
    'INPUT_CSV_DIR',
    'OUTPUT_CACHE_DIR', 'OUTPUT_TEMP_DIR', 'OUTPUT_GENERATED_DIR',
    'REPORTS_DIR', 'REPORTS_COMPLETED_DIR', 'REPORTS_WORKING_DIR',
    'DOCUMENT_DIR',
    'IMAGE_DIR', 'OUTPUT_CSV_DIR', 'CSV_DIR',
    'RESULT_DIR', 'RESEARCH_DIR', 'WORKING_DIR',

    # personal
    'CURRENT_AGE', 'CURRENT_YEAR', 'RETIREMENT_AGE', 'RETIREMENT_YEAR',
    'WIFE_AGE', 'ELDEST_CHILD_AGE', 'YOUNGEST_CHILD_AGE',
    'CURRENT_NISA', 'CURRENT_NISA_PRINCIPAL', 'CURRENT_NISA_GAIN',
    'CURRENT_IDECO', 'CURRENT_IDECO_PRINCIPAL', 'CURRENT_IDECO_GAIN',
    'CURRENT_COMPANY_STOCK', 'CURRENT_COMPANY_STOCK_COST', 'CURRENT_COMPANY_STOCK_GAIN',
    'CURRENT_CASH', 'TOTAL_ASSETS',
    'ANNUAL_INCOME_AFTER_TAX', 'MONTHLY_INCOME',
    'ANNUAL_RENT', 'MONTHLY_RENT',
    'CURRENT_MONTHLY_NISA', 'CURRENT_MONTHLY_IDECO', 'CURRENT_TOTAL_MONTHLY_INVESTMENT',
    'MONTHLY_IDECO_2027', 'MONTHLY_INVESTMENT_2027',
    'WIFE_MONTHLY_NISA',
    'NISA_LIFETIME_LIMIT', 'NISA_LIFETIME_REMAINING',
    'EDUCATION_COST', 'EDUCATION_COST_PER_CHILD',
    'RETIREMENT_GOAL',
    'MONTHLY_PENSION', 'ANNUAL_PENSION',
    'MONTHLY_RETIREMENT_SHORTFALL',

    # simulation
    'MONTE_CARLO_ITERATIONS',
    'EXPECTED_RETURN_STOCK', 'EXPECTED_RETURN_BOND', 'EXPECTED_RETURN_BALANCED',
    'VOLATILITY_STOCK', 'VOLATILITY_BOND', 'VOLATILITY_BALANCED',
    'DEFAULT_STOCK_RATIO', 'DEFAULT_BOND_RATIO',
    'DEFAULT_SIMULATION_YEARS',

    # constants
    'HIGH_RISK_THRESHOLD', 'MODERATE_RISK_THRESHOLD',
    'EMERGENCY_FUND_MONTHS', 'MINIMUM_CASH_RESERVE_MONTHS',
    'DEFAULT_INFLATION_RATE', 'HIGH_INFLATION_RATE',
    'TYPICAL_FUND_FEE', 'HIGH_FEE_THRESHOLD',
    'CAPITAL_GAINS_TAX_RATE',
    'NISA_ANNUAL_LIMIT', 'NISA_GROWTH_LIMIT',
    'IDECO_MONTHLY_LIMIT_EMPLOYEE', 'IDECO_MONTHLY_LIMIT_NO_PENSION', 'IDECO_WITHDRAWAL_AGE'
]
